name: OtoProxy Workflow

on:
  schedule:
    - cron: '0 */6 * * *' # Setiap 6 jam
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-otoproxy:
    runs-on: ubuntu-latest

    steps:
      - name: Check GitHub Token Permissions
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          echo "Checking GH_TOKEN permissions for RockyGerunX/OtoProxy"
          RESPONSE=$(curl -s -H "Authorization: Bearer $GH_TOKEN" -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/RockyGerunX/OtoProxy)
          if echo "$RESPONSE" | grep -q '"message": "Not Found"'; then
            echo "Error: Repository not found or GH_TOKEN is invalid"
            exit 1
          fi
          if echo "$RESPONSE" | grep -q '"permissions":.*"push": true'; then
            echo "GH_TOKEN has write access to the repository"
          else
            echo "Error: GH_TOKEN lacks write access to the repository"
            echo "Response: $RESPONSE"
            exit 1
          fi

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run OtoProxy
        run: python OtoProxy.py

      - name: Commit and push results
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add all-proxies.txt http-proxies.txt socks4-proxies.txt socks5-proxies.txt blacklist.txt
          git commit -m "Update proxy lists $(date +%Y%m%d_%H%M%S)" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
