name: OtoProxy Workflow

on:
  schedule:
    - cron: '0 */6 * * *' # Setiap 6 jam
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-otoproxy:
    runs-on: ubuntu-latest

    steps:
      - name: Check GH_TOKEN Availability
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          if [ -z "$GH_TOKEN" ]; then
            echo "Error: GH_TOKEN is not set or empty"
            exit 1
          else
            echo "GH_TOKEN is set"
          fi

      - name: Install jq
        run: |
          sudo apt-get update
          sudo apt-get install -y jq

      - name: Check GitHub Token Permissions
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          echo "Checking GH_TOKEN permissions for RockyGerunX/OtoProxy"
          RESPONSE=$(curl -s -H "Authorization: Bearer $GH_TOKEN" -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/RockyGerunX/OtoProxy)
          if [ -z "$RESPONSE" ]; then
            echo "Error: Empty response from GitHub API"
            exit 1
          fi
          if echo "$RESPONSE" | grep -q '"message": "Bad credentials"'; then
            echo "Error: GH_TOKEN is invalid or expired"
            exit 1
          fi
          if echo "$RESPONSE" | grep -q '"message": "Not Found"'; then
            echo "Error: Repository RockyGerunX/OtoProxy not found or inaccessible"
            exit 1
          fi
          PUSH_PERMISSION=$(echo "$RESPONSE" | jq -r '.permissions.push')
          echo "Push permission: $PUSH_PERMISSION"
          if [ "$PUSH_PERMISSION" = "true" ]; then
            echo "GH_TOKEN has write (push) access to the repository"
          else
            echo "Error: GH_TOKEN lacks write (push) access to the repository"
            echo "Full API Response: $RESPONSE"
            exit 1
          fi

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run OtoProxy
        run: python OtoProxy.py

      - name: Commit and push results
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add all-proxies.txt http-proxies.txt socks4-proxies.txt socks5-proxies.txt blacklist.txt
          git commit -m "Update proxy lists $(date +%Y%m%d_%H%M%S)" || echo "No changes to commit"
          git push https://x-access-token:$GH_TOKEN@github.com/RockyGerunX/OtoProxy.git
