name: OtoProxy Workflow

on:
  schedule:
    - cron: '0 */6 * * *' # Setiap 6 jam
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-otoproxy:
    runs-on: ubuntu-latest

    steps:
      - name: Check GH_TOKEN
        run: |
          if [ -z "${{ secrets.GH_TOKEN }}" ]; then
            echo "Error: GH_TOKEN is not set. Please add GH
            the GH_TOKEN secret in the repository settings."
            exit 1
          fi
          echo "GH_TOKEN is set."

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run OtoProxy
        run: python OtoProxy.py

      - name: Commit and push results
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add all-proxies.txt http-proxies.txt socks4-proxies.txt socks5-proxies.txt blacklist.txt
          git commit -m "Update proxy lists $(date +%Y%m%d_%H%M%S)" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/RockyGerunX/OtoProxy.git HEAD:main
