name: OtoProxy Scrape and Check
on:
  schedule:
    - cron: '0 */6 * * *'  # Jalankan setiap 6 jam
  workflow_dispatch:  # Izinkan jalankan manual
jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run scraper
        run: python scraper_checker.py

      - name: Commit and push results
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add result/ || echo "No files to add in result/"
          git diff --staged --quiet || git commit -m "Update proxy results $(date -u)"
          git push || echo "No changes to push"
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
